# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/colortextpy',
                'doc_host': 'https://susuky.github.io',
                'git_url': 'https://github.com/susuky/colortextpy',
                'lib_path': 'colortextpy'},
  'syms': { 'colortextpy.color': { 'colortextpy.color.Color': ('color.html#color', 'colortextpy/color.py'),
                                   'colortextpy.color.Color.__contains__': ('color.html#color.__contains__', 'colortextpy/color.py'),
                                   'colortextpy.color.Color.__init__': ('color.html#color.__init__', 'colortextpy/color.py'),
                                   'colortextpy.color.Color.bgr': ('color.html#color.bgr', 'colortextpy/color.py'),
                                   'colortextpy.color.Color.hex': ('color.html#color.hex', 'colortextpy/color.py'),
                                   'colortextpy.color.Color.rgb': ('color.html#color.rgb', 'colortextpy/color.py'),
                                   'colortextpy.color.EnumMeta': ('color.html#enummeta', 'colortextpy/color.py'),
                                   'colortextpy.color.EnumMeta.__repr__': ('color.html#enummeta.__repr__', 'colortextpy/color.py'),
                                   'colortextpy.color.EnumMeta.__str__': ('color.html#enummeta.__str__', 'colortextpy/color.py'),
                                   'colortextpy.color.EnumMeta.available': ('color.html#enummeta.available', 'colortextpy/color.py'),
                                   'colortextpy.color.EnumMeta.str': ('color.html#enummeta.str', 'colortextpy/color.py')}}}
